### ISSUE TITLE
Data Source sharing between Vaadin & Spring

### ISSUE THREAD

**Issue by nfrankel** [peholmst/vaadin4spring#92] opened 2014-11-26 17:37 UTC
I've tried to wrap the provided Spring Boot's DataSource in a J2EEConnectionPool and it seems Vaadin faces SQLRecoverableException with "Closed Connection" labels.

For me, the fix was to replace the default data source with my own bean that does a JNDI lookup in the application server.

I'd suggest either fixing the issue or at least providing this workaround in the documentation.

**Comment by peholmst** [comment] 2015-01-15 13:32
I'll leave this open for now, but I suspect the problem is with Spring Boot and not the Vaadin add-on.

**Comment by nfrankel** [comment] 2015-01-15 13:34
I didn't have time to re-check.

**Comment by peholmst** [comment] 2015-09-18 08:37
Closing since there has not been any activity for many months.

**Closed by peholmst** 2015-09-18 08:37 UTC
Labels: investigating
